### ISSUE TITLE
Set up Redux store

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/comet_planning#1]
## Description
The Redux data store is a single source of truth for the Comet Planning app. It contains app state and exposes actions to modify user and (primarily) schedule data.

## Tasks
The Redux store needs to contain state for the current courses displayed on the screen but also contain actions to do the following:
- [ ] Add a course to a given semester from a course plan
- [ ] Remove a course from a given semester
- [ ] Move a course between semesters
