### ISSUE TITLE
Set up routing

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/comet_planning#2]
## Description
Although Comet Planning is a single-page application, routing will make URLs more semantic and allow specific functionality to be separated into different pages. This will allow standard browser "back" functionality to function as intended and aid the user experience.

## Tasks
The app will support a few different pages:
- [x] `/` - The landing page, provides information about the app when no user is authenticated
- [ ] `/schedules` - A list of all the currently authenticated user's schedules
- [ ] `/schedules/:id` - A viewing page displaying schedule information and ability to input grades for attempted courses
- [ ] `/schedules/:id/plan` - The primary page where schedules are edited
- [ ] `/auth` - A page to sign in or be referred to a third-party identity provider
