### ISSUE TITLE
Creating the Different Bars

### ISSUE THREAD

**Issue by medhaaiyah** [acmutd/comet_planning#8]
## Problem Description

This is issue will establish the main UI components of our website. The top bar to navigate, the sidebar where the classes for the degree plan are included, and the semester bar where the user will create their four year will be created

## Task List

 - [ ] Finish creating the top bar
 - [ ] Finish creating the side bar
 - [ ] Finish creating the semester bar
